# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kopr < Formula
  desc "CLI tool for creating GitHub PRs with Conventional Commits format"
  homepage "https://github.com/dangrondahl/kopr"
  version "0.1.0-beta.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dangrondahl/kopr/releases/download/v0.1.0-beta.1/kopr_0.1.0-beta.1_Darwin_x86_64.tar.gz"
      sha256 "91930b1df14651a6b5f344e97435dc2fa9d74f5dc8ca3e0f0af7aa567031839e"

      def install
        bin.install "kopr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dangrondahl/kopr/releases/download/v0.1.0-beta.1/kopr_0.1.0-beta.1_Darwin_arm64.tar.gz"
      sha256 "87e29969b420b9747bca3c83dc26fe30135134f8ced364e74f2939f16ebc48aa"

      def install
        bin.install "kopr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dangrondahl/kopr/releases/download/v0.1.0-beta.1/kopr_0.1.0-beta.1_Linux_x86_64.tar.gz"
      sha256 "377f56bd45fa43dcd75222796555365407993809e7fa86bae180a5f243637b25"
      def install
        bin.install "kopr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dangrondahl/kopr/releases/download/v0.1.0-beta.1/kopr_0.1.0-beta.1_Linux_arm64.tar.gz"
      sha256 "c34f523f65e84dd197c03b3d4ec376b2b4200e757c262ac2773ca2bf3ed5e3ac"
      def install
        bin.install "kopr"
      end
    end
  end

  def caveats
    <<~EOS
      On macOS, you may need to bypass Gatekeeper security for unsigned binaries:
        xattr -d com.apple.quarantine $(which kopr)
      Or allow via System Preferences > Security & Privacy > "Allow Anyway"
    EOS
  end

  test do
    system "#{bin}/kopr --version"
  end
end
