# This file was generated by GoReleaser. DO NOT EDIT.
cask "kopr" do
  name "kopr"
  desc "CLI tool for creating GitHub PRs with Conventional Commits format"
  homepage "https://github.com/dangrondahl/kopr"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kopr"

  on_macos do
    on_intel do
      url "https://github.com/dangrondahl/kopr/releases/download/v#{version}/kopr_#{version}_Darwin_x86_64.tar.gz"
      sha256 "49c85ca40069d4a69f2aae4fbeda01013fd02bec8baeece97e9344a3881691ef"
    end
    on_arm do
      url "https://github.com/dangrondahl/kopr/releases/download/v#{version}/kopr_#{version}_Darwin_arm64.tar.gz"
      sha256 "46cd4c8912e9417eb6e198fb48c6316a3453694b723e0b6ce6ce845d4fadb652"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dangrondahl/kopr/releases/download/v#{version}/kopr_#{version}_Linux_x86_64.tar.gz"
      sha256 "780a659f14732d578507decf43b650052b2884065642e419c5712ed06aec7010"
    end
    on_arm do
      url "https://github.com/dangrondahl/kopr/releases/download/v#{version}/kopr_#{version}_Linux_arm64.tar.gz"
      sha256 "cd8bbb6d5fdf31796a19d2177a7096f56c890192023587841f94fd9f6b7839e0"
    end
  end

  caveats do
    "On macOS, you may need to bypass Gatekeeper security for unsigned binaries:"
    "  xattr -d com.apple.quarantine $(which kopr)"
    "Or allow via System Preferences > Security & Privacy > "Allow Anyway""
  end

  # No zap stanza required
end
