# This file was generated by GoReleaser. DO NOT EDIT.
cask "kopr" do
  name "kopr"
  desc "CLI tool for creating GitHub PRs with Conventional Commits format"
  homepage "https://github.com/dangrondahl/kopr"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kopr"

  on_macos do
    on_intel do
      url "https://github.com/dangrondahl/kopr/releases/download/v#{version}/kopr_#{version}_Darwin_x86_64.tar.gz"
      sha256 "753f00dd3d876dac9ccce30bd47f7959a7092e3ddbb1998379c13bbd039cdba0"
    end
    on_arm do
      url "https://github.com/dangrondahl/kopr/releases/download/v#{version}/kopr_#{version}_Darwin_arm64.tar.gz"
      sha256 "0a1af00a198482da0518a55ab13b1acc951e24259a6f611bdc93f185f8d13382"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dangrondahl/kopr/releases/download/v#{version}/kopr_#{version}_Linux_x86_64.tar.gz"
      sha256 "d453786cd3cc5754100ed22aebe00c01d32e152ed55a2eee966bb329d3b59a0f"
    end
    on_arm do
      url "https://github.com/dangrondahl/kopr/releases/download/v#{version}/kopr_#{version}_Linux_arm64.tar.gz"
      sha256 "2e80ef89cce9715d3301fea7161d35ca3ba73a09e0b9c7a5deaad61805df2907"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kopr"]
    end
  end

  caveats do
    "This binary is not signed or notarized. The installer automatically removes"
    "the quarantine attribute to allow the binary to run on macOS."
  end

  # No zap stanza required
end
